# Generated by Django 5.2.6 on 2026-05-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('token_mint', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_url', models.URLField(blank=True, null=True)),
                ('bags_url', models.URLField(blank=True, null=True)),
                ('launch_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('is_launched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
