# Generated by Django 5.2.6 on 2026-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVerse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecotoken',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
