# Generated by Django 5.2.6 on 2026-05-14 15:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVerse_app', '0002_ecotoken_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=30)),
                ('user_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('waste_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('center_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('reward_pending', 'Reward Pending'), ('reward_sent', 'Reward Sent'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
