# Generated by Django 5.2.6 on 2026-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoVerse_app', '0003_recyclingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingsubmission',
            name='reward_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclingsubmission',
            name='reward_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
